#!/usr/bin/env bash
#
# Bootstrap a minimal Traefik instance for the firecrawl stack.
#
# What this does:
#   - Creates an external `traefik` Docker network (if missing).
#   - Writes /opt/traefik/{traefik.yml, docker-compose.yml, acme.json, .env}.
#   - Brings Traefik up listening on :80 + :443.
#   - Configures a `cloudflare` cert resolver doing DNS-01 challenges via
#     the Cloudflare DNS API.
#
# What you still own (manual UI steps, see closing message):
#   - DNS records pointing at this server's public IP.
#   - Cloudflare Access apps for the dashboard + MCP hostnames (returns the
#     CF_ACCESS_AUD_* values you paste into ~/firecrawl-stack/.env).
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/TheophilusChinomona/firecrawl/release/deploy/setup-traefik.sh | bash
#
#   Or install.sh can call this for you when no Traefik is detected.
#
# Env knobs (all optional — script prompts when unset):
#   TRAEFIK_DIR          where to install Traefik          (default /opt/traefik)
#   TRAEFIK_NETWORK      Docker network name               (default traefik)
#   TRAEFIK_EMAIL        ACME registration email           (prompted)
#   CF_DNS_API_TOKEN     Cloudflare token w/ Zone:DNS:Edit (prompted, hidden)

set -euo pipefail

TRAEFIK_DIR="${TRAEFIK_DIR:-/opt/traefik}"
TRAEFIK_NETWORK="${TRAEFIK_NETWORK:-traefik}"
TRAEFIK_EMAIL="${TRAEFIK_EMAIL:-}"
CF_DNS_API_TOKEN="${CF_DNS_API_TOKEN:-}"

bold()  { printf "\033[1m%s\033[0m\n" "$*"; }
info()  { printf "  %s\n" "$*"; }
warn()  { printf "\033[33m  %s\033[0m\n" "$*"; }
fail()  { printf "\033[31mERROR: %s\033[0m\n" "$*" >&2; exit 1; }

ask() {
  local prompt="$1" default="${2:-}" reply
  if [ -t 0 ]; then
    read -rp "$prompt" reply
  else
    read -rp "$prompt" reply </dev/tty || reply="$default"
  fi
  echo "${reply:-$default}"
}

ask_secret() {
  local prompt="$1" reply
  if [ -t 0 ]; then
    read -rsp "$prompt" reply
  else
    read -rsp "$prompt" reply </dev/tty
  fi
  echo
  printf '%s' "$reply"
}

bold "Traefik bootstrap for the firecrawl stack"
echo

# Preflight
command -v docker &>/dev/null || fail "docker is required."
docker compose version &>/dev/null || fail "docker compose v2 plugin is required."

# Idempotency guard: if a Traefik is already running, leave it alone.
RUNNING_TRAEFIK="$(docker ps --filter ancestor=traefik:v3 --format '{{.Names}}' 2>/dev/null | head -1)"
if [ -z "$RUNNING_TRAEFIK" ]; then
  RUNNING_TRAEFIK="$(docker ps --filter ancestor=traefik --format '{{.Names}}' 2>/dev/null | head -1)"
fi
if [ -n "$RUNNING_TRAEFIK" ]; then
  bold "Traefik already running ($RUNNING_TRAEFIK) — leaving it alone"
  exit 0
fi

# Network
if ! docker network inspect "$TRAEFIK_NETWORK" &>/dev/null; then
  bold "Creating '$TRAEFIK_NETWORK' Docker network"
  docker network create "$TRAEFIK_NETWORK" >/dev/null
else
  info "  ✓ '$TRAEFIK_NETWORK' network already exists"
fi

# Prompt for email + CF token if not in env
if [ -z "$TRAEFIK_EMAIL" ]; then
  TRAEFIK_EMAIL=$(ask "ACME registration email (Let's Encrypt sends cert renewal notices here): ")
fi
[ -n "$TRAEFIK_EMAIL" ] || fail "TRAEFIK_EMAIL is required."

if [ -z "$CF_DNS_API_TOKEN" ]; then
  echo
  warn "Need a Cloudflare API token with Zone:DNS:Edit on your domain."
  warn "  Create at: https://dash.cloudflare.com/profile/api-tokens"
  warn "  Template: 'Edit zone DNS' (limited to your zone)."
  CF_DNS_API_TOKEN=$(ask_secret "Paste CF_DNS_API_TOKEN (input hidden): ")
fi
[ -n "$CF_DNS_API_TOKEN" ] || fail "CF_DNS_API_TOKEN is required."

# Sanity-check the token (optional but cheap)
TOKEN_VERIFY="$(curl -s -H "Authorization: Bearer $CF_DNS_API_TOKEN" \
  https://api.cloudflare.com/client/v4/user/tokens/verify | grep -o '"status":"active"' || true)"
if [ -z "$TOKEN_VERIFY" ]; then
  warn "Cloudflare token didn't verify as active. Continuing anyway — Traefik will fail loudly on first cert request if it's bad."
else
  info "  ✓ Cloudflare token verified active"
fi

# Make install dir (root-owned is fine; need sudo if not /opt-writable)
if [ ! -w "$(dirname "$TRAEFIK_DIR")" ] && [ ! -d "$TRAEFIK_DIR" ]; then
  warn "Creating $TRAEFIK_DIR with sudo"
  sudo mkdir -p "$TRAEFIK_DIR"
  sudo chown "$(whoami)" "$TRAEFIK_DIR"
fi
mkdir -p "$TRAEFIK_DIR"
cd "$TRAEFIK_DIR"

bold "Writing config to $TRAEFIK_DIR"

cat > traefik.yml <<EOF
# Generated by setup-traefik.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false
    network: $TRAEFIK_NETWORK

certificatesResolvers:
  cloudflare:
    acme:
      email: $TRAEFIK_EMAIL
      storage: /acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - 1.1.1.1:53
          - 8.8.8.8:53

# Optional: enable the dashboard on a private port (uncomment to use).
# api:
#   dashboard: true
EOF

cat > docker-compose.yml <<EOF
services:
  traefik:
    image: traefik:v3
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - $TRAEFIK_NETWORK
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./acme.json:/acme.json
    environment:
      CF_DNS_API_TOKEN: \${CF_DNS_API_TOKEN}
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  $TRAEFIK_NETWORK:
    external: true
EOF

# Cloudflare provider in Traefik reads CF_DNS_API_TOKEN from env.
# Keep it in a .env next to compose with restrictive perms.
umask 077
cat > .env <<EOF
CF_DNS_API_TOKEN=$CF_DNS_API_TOKEN
EOF
umask 022

# acme.json must be 0600 or Traefik refuses to use it.
[ -f acme.json ] || touch acme.json
chmod 600 acme.json

bold "Starting Traefik"
docker compose up -d

echo
bold "Done"
cat <<EOF

  Traefik is up. Watch logs:  cd $TRAEFIK_DIR && docker compose logs -f

  Remaining manual setup:

  1. DNS records — point at this server's public IP:
       crawl.<yourdomain>   A   <public-ip>
       enrich.<yourdomain>  A   <public-ip>

     Or CNAMEs through Cloudflare's proxy (orange cloud must be ON for
     Cloudflare Access to gate traffic).

  2. Cloudflare Access apps (Zero Trust → Access → Applications → Add):

       App #1 (Dashboard):
         Type:   Self-hosted
         Domain: enrich.<yourdomain>
         Policy: allow specific emails / your team
         Save → copy the Application Audience (AUD) Tag → that's
                CF_ACCESS_AUD_DASHBOARD in your firecrawl-stack/.env

       App #2 (MCP):
         Type:   Self-hosted
         Domain: crawl.<yourdomain>   Path: /mcp/*
         Policy: allow specific emails / a service token for AI agents
         Save → that's CF_ACCESS_AUD_MCP

       Team subdomain (the bit before .cloudflareaccess.com) is
       CF_ACCESS_TEAM.

  3. Update ~/firecrawl-stack/.env with those three CF_ACCESS_* values
     and the OPERATOR_EMAILS allowlist, then:

       cd ~/firecrawl-stack && docker compose up -d

     (or just wait — Watchtower will roll labeled containers when you
      next push to release).

  4. Smoke test:

       curl -I https://crawl.<yourdomain>      # should 302 to Cloudflare Access
       curl -I https://enrich.<yourdomain>     # should 302 to Cloudflare Access

EOF
